"""Refresh the IDE-portable copy; tests require byte-identical shared behavior."""
from pathlib import Path
folder=Path(__file__).resolve().parent
source=folder.parent/'uno_pca9685/uno_pca9685.ino'
(folder/'pca_core.h').write_bytes(b'// GENERATED by sync_core.py; do not edit separately.\n'+source.read_bytes())
