"""Install only the FIGBOT module path shim, preserving other FreeCAD modules."""
from pathlib import Path
import sys
import FreeCAD as App

ROOT=Path(__file__).resolve().parents[1]
module=Path(App.getUserAppDataDir())/'Mod/FIGBOT_Parametric'
module.mkdir(parents=True,exist_ok=True)
content=('# FIGBOT parametric bridge path shim; generated by FIGBOT\n'
         'import sys\n'
         f'for p in ({str(ROOT)!r}, {str(ROOT/"cad/freecad")!r}):\n'
         '    if p not in sys.path: sys.path.insert(0,p)\n'
         'import figbot_freecad\n')
path=module/'Init.py'
if path.exists() and 'FIGBOT parametric bridge path shim' not in path.read_text(encoding='utf-8'):
    raise RuntimeError('Refusing to overwrite unknown existing module')
path.write_text(content,encoding='utf-8')
print('Installed',path,flush=True)
